#!/usr/bin/env python3
"""HoI4 Mod Generator - YAML → HoI4 mod files (and back)"""

import yaml
import sys
import time
import shutil
import zipfile
import re
import json
from pathlib import Path

G = "\033[32m"; Y = "\033[33m"; R = "\033[31m"; B = "\033[36m"; X = "\033[0m"
HEADER = "# Generated by hoi4yaml - https://github.com/you/hoi4yaml\n\n"

_file_count = 0
_warn_count = 0


# ── Clausewitz writer ────────────────────────────────────────

def fmt(v):
    if isinstance(v, bool):
        return "yes" if v else "no"
    if isinstance(v, str) and (" " in v or not v):
        return f'"{v}"'
    return str(v)


def to_clausewitz(data, indent=0):
    pad = "\t" * indent
    out = []
    if isinstance(data, dict):
        for key, value in data.items():
            if key.startswith("_"):
                continue
            if isinstance(value, list) and value and isinstance(value[0], dict):
                for item in value:
                    out.append(f"{pad}{key} = {{")
                    out.append(to_clausewitz(item, indent + 1))
                    out.append(f"{pad}}}")
            elif isinstance(value, list):
                out.append(f"{pad}{key} = {{ {' '.join(fmt(v) for v in value)} }}")
            elif isinstance(value, dict):
                out.append(f"{pad}{key} = {{")
                out.append(to_clausewitz(value, indent + 1))
                out.append(f"{pad}}}")
            else:
                out.append(f"{pad}{key} = {fmt(value)}")
    return "\n".join(filter(None, out))


# ── Clausewitz reader (for --import) ────────────────────────

def parse_clausewitz(text):
    tokens = re.findall(r'"[^"]*"|\{|\}|[^\s{}]+', text)
    pos = [0]

    def peek():
        while pos[0] < len(tokens) and tokens[pos[0]].startswith("#"):
            pos[0] += 1
        return tokens[pos[0]] if pos[0] < len(tokens) else None

    def consume():
        t = peek()
        pos[0] += 1
        return t

    def parse_block():
        result = {}
        while peek() and peek() != "}":
            key = consume()
            if peek() == "=":
                consume()  # =
                if peek() == "{":
                    consume()  # {
                    val = parse_block()
                    consume()  # }
                else:
                    raw = consume()
                    val = raw.strip('"')
                    if val == "yes":
                        val = True
                    elif val == "no":
                        val = False
                    else:
                        try:
                            val = int(val)
                        except ValueError:
                            try:
                                val = float(val)
                            except ValueError:
                                pass
            else:
                val = True
            # Handle duplicate keys → list
            if key in result:
                if not isinstance(result[key], list):
                    result[key] = [result[key]]
                result[key].append(val)
            else:
                result[key] = val
        return result

    # Strip comments
    text = re.sub(r'#[^\n]*', '', text)
    tokens = re.findall(r'"[^"]*"|\{|\}|[^\s{}]+', text)
    return parse_block()


# ── Helpers ──────────────────────────────────────────────────

def write(path, content, dry_run=False):
    global _file_count
    if dry_run:
        print(f"  {B}[dry-run]{X} {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(HEADER + content, encoding="utf-8-sig")
    _file_count += 1
    print(f"  {G}+{X} {path}")


def warn(msg):
    global _warn_count
    _warn_count += 1
    print(f"  {Y}[WARN]{X} {msg}")


def apply_vars(data, variables):
    if isinstance(data, str):
        for k, v in variables.items():
            data = data.replace(f"${k}", str(v))
        return data
    if isinstance(data, dict):
        return {k: apply_vars(v, variables) for k, v in data.items()}
    if isinstance(data, list):
        return [apply_vars(i, variables) for i in data]
    return data


def apply_templates(data, templates):
    if isinstance(data, dict):
        if "_template" in data:
            base = templates.get(data["_template"], {}).copy()
            base.update({k: v for k, v in data.items() if k != "_template"})
            data = base
        return {k: apply_templates(v, templates) for k, v in data.items()}
    if isinstance(data, list):
        return [apply_templates(item, templates) for item in data]
    return data


def apply_conditions(data):
    """Remove entries where _if evaluates to false."""
    if isinstance(data, dict):
        if data.get("_if") is False:
            return None
        return {k: apply_conditions(v) for k, v in data.items() if apply_conditions(v) is not None}
    if isinstance(data, list):
        result = [apply_conditions(i) for i in data]
        return [i for i in result if i is not None]
    return data


CACHE_FILE = Path(__file__).parent / ".hoi4cache.json"

def _load_cache():
    if not CACHE_FILE.exists():
        return None
    try:
        data = json.loads(CACHE_FILE.read_text(encoding="utf-8"))
        hoi4 = find_hoi4_path()
        if hoi4:
            check_paths = [hoi4 / "common/national_focus", hoi4 / "common/units/equipment",
                           hoi4 / "common/units", hoi4 / "common/resources"]
            mtime = max((p.stat().st_mtime for p in check_paths if p.exists()), default=0)
            if data.get("mtime") != mtime:
                return None
        return data
    except Exception:
        return None

def _save_cache(data):
    try:
        hoi4 = find_hoi4_path()
        if hoi4:
            check_paths = [hoi4 / "common/national_focus", hoi4 / "common/units/equipment",
                           hoi4 / "common/units", hoi4 / "common/resources"]
            data["mtime"] = max((p.stat().st_mtime for p in check_paths if p.exists()), default=0)
        CACHE_FILE.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")
    except Exception:
        pass


def load_game_maps(hoi4_path):
    """Build state/country/ideology/trait/tech_category maps from game files."""
    # States: parse id + STATE_KEY + VP province from history/states/*.txt
    state_key_to_id = {}
    state_key_to_province = {}
    for f in (hoi4_path / "history/states").glob("*.txt"):
        text = f.read_text(encoding="utf-8-sig", errors="ignore")
        id_m  = re.search(r'\bid\s*=\s*(\d+)', text)
        key_m = re.search(r'\bname\s*=\s*"(STATE_\d+)"', text)
        if id_m and key_m:
            state_key_to_id[key_m.group(1)] = int(id_m.group(1))
            vp_m = re.search(r'victory_points\s*=\s*\{\s*(\d+)', text)
            prov_m = re.search(r'provinces\s*=\s*\{[^}]*?(\d+)', text, re.DOTALL)
            prov = int(vp_m.group(1)) if vp_m else (int(prov_m.group(1)) if prov_m else None)
            if prov:
                state_key_to_province[key_m.group(1)] = prov

    state_name_to_id = {}
    state_name_to_province = {}
    loc_file = hoi4_path / "localisation/english/state_names_l_english.yml"
    if loc_file.exists():
        for m in re.finditer(r'(STATE_\d+):0\s+"([^"]+)"', loc_file.read_text(encoding="utf-8-sig", errors="ignore")):
            key, name = m.group(1), m.group(2)
            nl = name.lower()
            if key in state_key_to_id:
                state_name_to_id[nl] = state_key_to_id[key]
            if key in state_key_to_province:
                state_name_to_province[nl] = state_key_to_province[key]

    country_name_to_tag = {}
    tag_order = []
    for f in sorted((hoi4_path / "common/country_tags").glob("*.txt")):
        for tag in re.findall(r'^([A-Z]{3})\s*=', f.read_text(encoding="utf-8-sig", errors="ignore"), re.MULTILINE):
            tag_order.append(tag)
    loc_dir = hoi4_path / "localisation/english"
    loc_texts = [f.read_text(encoding="utf-8-sig", errors="ignore")
                 for f in loc_dir.glob("*.yml") if f.exists()]
    combined = "\n".join(loc_texts)
    for tag in tag_order:
        m = re.search(rf'^\s*{tag}:0\s+"([^"]+)"', combined, re.MULTILINE)
        if m:
            name = m.group(1).lower()
            if name not in country_name_to_tag:
                country_name_to_tag[name] = tag

    # Ideologies: group names (democratic, fascism, ...) + sub-types (conservatism, ...)
    ideologies = set()
    for f in (hoi4_path / "common/ideologies").glob("*.txt"):
        text = f.read_text(encoding="utf-8-sig", errors="ignore")
        # Top-level ideology names
        for m in re.finditer(r'^\s*(\w+)\s*=\s*\{', text, re.MULTILINE):
            ideologies.add(m.group(1))
        # Sub-types inside types = { ... }
        for block in re.findall(r'types\s*=\s*\{([^}]+)\}', text, re.DOTALL):
            for m in re.finditer(r'(\w+)\s*=\s*\{', block):
                ideologies.add(m.group(1))
    ideologies -= {"types", "dynamic_faction_names", "color", "war_impact_on_world_tension",
                   "faction_impact_on_world_tension", "rules", "can_be_randomly_selected"}

    # Traits: separate country_leader vs unit_leader
    country_leader_traits = set()
    unit_leader_traits = set()
    for f in (hoi4_path / "common/country_leader").glob("*.txt"):
        text = f.read_text(encoding="utf-8-sig", errors="ignore")
        for block in re.findall(r'leader_traits\s*=\s*\{(.+?)^\}', text, re.DOTALL | re.MULTILINE):
            for m in re.finditer(r'^\t(\w+)\s*=\s*\{', block, re.MULTILINE):
                country_leader_traits.add(m.group(1))
    for f in (hoi4_path / "common/unit_leader").glob("*.txt"):
        text = f.read_text(encoding="utf-8-sig", errors="ignore")
        for block in re.findall(r'leader_traits\s*=\s*\{(.+?)^\}', text, re.DOTALL | re.MULTILINE):
            for m in re.finditer(r'^\t(\w+)\s*=\s*\{', block, re.MULTILINE):
                unit_leader_traits.add(m.group(1))
    traits = country_leader_traits | unit_leader_traits

    # Technology categories
    tech_categories = set()
    tag_file = hoi4_path / "common/technology_tags/00_technology.txt"
    if tag_file.exists():
        for m in re.finditer(r'^\s+(\w+)\s*$', tag_file.read_text(encoding="utf-8-sig", errors="ignore"), re.MULTILINE):
            tech_categories.add(m.group(1))

    # Building max levels from common/buildings
    building_max = {}
    for f in (hoi4_path / "common/buildings").glob("*.txt"):
        text = f.read_text(encoding="utf-8-sig", errors="ignore")
        for m in re.finditer(r'^\t(\w+)\s*=\s*\{', text, re.MULTILINE):
            name = m.group(1)
            snippet = text[m.start():m.start()+600]
            cap = re.search(r'level_cap\s*=\s*\{([^}]+)\}', snippet, re.DOTALL)
            if cap:
                sm = re.search(r'state_max\s*=\s*(\d+)', cap.group(1))
                if sm:
                    building_max[name] = int(sm.group(1))

    # Resources
    resources = set()
    for f in (hoi4_path / "common/resources").glob("*.txt"):
        for m in re.finditer(r'^\t(\w+)\s*=\s*\{', f.read_text(encoding="utf-8-sig", errors="ignore"), re.MULTILINE):
            resources.add(m.group(1))

    # Sub-unit types (division unit types)
    sub_units = set()
    for f in (hoi4_path / "common/units").glob("*.txt"):
        text = f.read_text(encoding="utf-8-sig", errors="ignore")
        for block in re.findall(r'sub_units\s*=\s*\{(.+?)^\}', text, re.DOTALL | re.MULTILINE):
            for m in re.finditer(r'^\t(\w+)\s*=\s*\{', block, re.MULTILINE):
                sub_units.add(m.group(1))

    # Equipment types
    equipment_types = set()
    for f in (hoi4_path / "common/units/equipment").glob("*.txt"):
        text = f.read_text(encoding="utf-8-sig", errors="ignore")
        for block in re.findall(r'^equipments\s*=\s*\{(.+?)^\}', text, re.DOTALL | re.MULTILINE):
            for m in re.finditer(r'^\t(\w+)\s*=\s*\{', block, re.MULTILINE):
                equipment_types.add(m.group(1))

    # Wargoal types
    wargoal_types = set()
    for f in (hoi4_path / "common/wargoals").glob("*.txt"):
        text = f.read_text(encoding="utf-8-sig", errors="ignore")
        for block in re.findall(r'wargoal_types\s*=\s*\{(.+?)^\}', text, re.DOTALL | re.MULTILINE):
            for m in re.finditer(r'^\t(\w+)\s*=\s*\{', block, re.MULTILINE):
                wargoal_types.add(m.group(1))

    # Modifier names (from ideas modifier blocks + modifier_definitions)
    modifier_names = set()
    for f in (hoi4_path / "common/ideas").glob("*.txt"):
        for block in re.findall(r'modifier\s*=\s*\{([^}]+)\}', f.read_text(encoding="utf-8-sig", errors="ignore")):
            for m in re.finditer(r'\t\t\t(\w+)\s*=', block):
                modifier_names.add(m.group(1))
    for f in (hoi4_path / "common/modifier_definitions").glob("*.txt"):
        for m in re.finditer(r'^\t(\w+)\s*=\s*\{', f.read_text(encoding="utf-8-sig", errors="ignore"), re.MULTILINE):
            modifier_names.add(m.group(1))

    return state_name_to_id, state_name_to_province, country_name_to_tag, ideologies, traits, tech_categories, building_max, country_leader_traits, unit_leader_traits, resources, sub_units, equipment_types, wargoal_types, modifier_names

_state_map = None
_province_map = None
_country_map = None
_ideology_set = None
_trait_set = None
_country_leader_trait_set = None
_unit_leader_trait_set = None
_tech_category_set = None
_building_max = None
_resource_set = None
_sub_unit_set = None
_equipment_type_set = None
_wargoal_type_set = None
_modifier_name_set = None
_extra_state_map = {}

def get_game_maps():
    global _state_map, _province_map, _country_map, _ideology_set, _trait_set
    global _country_leader_trait_set, _unit_leader_trait_set, _tech_category_set, _building_max
    global _resource_set, _sub_unit_set, _equipment_type_set, _wargoal_type_set, _modifier_name_set
    if _state_map is None:
        cache = _load_cache()
        if cache and "state_map" in cache:
            _state_map = {k: int(v) for k, v in cache["state_map"].items()}
            _province_map = {k: int(v) for k, v in cache.get("province_map", {}).items()}
            _country_map = cache["country_map"]
            _ideology_set = set(cache.get("ideologies", []))
            _trait_set = set(cache.get("traits", []))
            _country_leader_trait_set = set(cache.get("country_leader_traits", []))
            _unit_leader_trait_set = set(cache.get("unit_leader_traits", []))
            _tech_category_set = set(cache.get("tech_categories", []))
            _building_max = cache.get("building_max", {})
            _resource_set = set(cache.get("resources", []))
            _sub_unit_set = set(cache.get("sub_units", []))
            _equipment_type_set = set(cache.get("equipment_types", []))
            _wargoal_type_set = set(cache.get("wargoal_types", []))
            _modifier_name_set = set(cache.get("modifier_names", []))
        else:
            hoi4 = find_hoi4_path()
            if hoi4:
                (_state_map, _province_map, _country_map, _ideology_set, _trait_set,
                 _tech_category_set, _building_max, _country_leader_trait_set, _unit_leader_trait_set,
                 _resource_set, _sub_unit_set, _equipment_type_set,
                 _wargoal_type_set, _modifier_name_set) = load_game_maps(hoi4)
                c = _load_cache() or {}
                c.update({"state_map": _state_map, "province_map": _province_map,
                          "country_map": _country_map, "ideologies": list(_ideology_set),
                          "traits": list(_trait_set),
                          "country_leader_traits": list(_country_leader_trait_set),
                          "unit_leader_traits": list(_unit_leader_trait_set),
                          "tech_categories": list(_tech_category_set),
                          "building_max": _building_max,
                          "resources": list(_resource_set),
                          "sub_units": list(_sub_unit_set),
                          "equipment_types": list(_equipment_type_set),
                          "wargoal_types": list(_wargoal_type_set),
                          "modifier_names": list(_modifier_name_set)})
                _save_cache(c)
            else:
                _state_map, _province_map, _country_map = {}, {}, {}
                _ideology_set, _trait_set, _tech_category_set, _building_max = set(), set(), set(), {}
                _country_leader_trait_set, _unit_leader_trait_set = set(), set()
                _resource_set, _sub_unit_set, _equipment_type_set = set(), set(), set()
                _wargoal_type_set, _modifier_name_set = set(), set()
    combined_state = {**_state_map, **_extra_state_map}
    return combined_state, _province_map, _country_map


def resolve_state(value):
    if isinstance(value, int):
        return value
    state_map, _, _ = get_game_maps()
    key = str(value).lower()
    if key in state_map:
        return state_map[key]
    import difflib
    close = difflib.get_close_matches(key, state_map.keys(), n=3, cutoff=0.5)
    hint = f" — did you mean: {[f'{n}={state_map[n]}' for n in close]}?" if close else ""
    raise ValueError(f"Unknown state: '{value}'{hint}")


def resolve_location(value):
    if isinstance(value, int):
        return value
    _, province_map, _ = get_game_maps()
    key = str(value).lower()
    if key in province_map:
        return province_map[key]
    return resolve_state(value)


def resolve_tag(value):
    if isinstance(value, str) and re.match(r'^[A-Z]{3}$', value):
        return value
    _, _, country_map = get_game_maps()
    key = str(value).lower()
    if key in country_map:
        return country_map[key]
    import difflib
    close = difflib.get_close_matches(key, country_map.keys(), n=3, cutoff=0.5)
    hint = f" — did you mean: {[f'{n}={country_map[n]}' for n in close]}?" if close else ""
    raise ValueError(f"Unknown country: '{value}'{hint}")


def resolve_game_refs(data):
    """Resolve state names → IDs and country names → tags recursively."""
    if isinstance(data, list):
        return [resolve_game_refs(i) for i in data]
    if not isinstance(data, dict):
        return data
    out = {}
    for k, v in data.items():
        if k == "location" and isinstance(v, str) and not v.isdigit():
            try:
                out[k] = resolve_location(v)
            except ValueError as e:
                warn(str(e)); out[k] = v
        elif k == "capital" and isinstance(v, str) and not v.isdigit():
            try:
                out[k] = resolve_state(v)
            except ValueError as e:
                warn(str(e)); out[k] = v
        elif k in ("owner", "controller", "tag", "add_core_of", "remove_core_of",
                   "original_tag", "default_country") and isinstance(v, str) and not re.match(r'^[A-Z]{3}$', v):
            try:
                out[k] = resolve_tag(v)
            except ValueError as e:
                warn(str(e)); out[k] = v
        else:
            out[k] = resolve_game_refs(v)
    return out


def expand_events(entries):
    result = []
    for entry in entries:
        entry = dict(entry)
        for etype in ("country_event", "news_event", "state_event"):
            if etype not in entry:
                continue
            expanded = []
            for ev in entry[etype]:
                ev = dict(ev)
                eid = ev.get("id", "")
                ev.setdefault("title", f"{eid}.t")
                ev.setdefault("desc",  f"{eid}.d")
                if "option" in ev:
                    ev["option"] = [
                        dict(opt, name=opt.get("name", f"{eid}.{chr(ord('a') + i)}"))
                        for i, opt in enumerate(ev["option"])
                    ]
                expanded.append(ev)
            entry[etype] = expanded
        result.append(entry)
    return result


ICON_HINTS_FALLBACK = {
    "industry": "GFX_focus_generic_industry_1",
    "factory":  "GFX_focus_generic_industry_2",
    "manpower": "GFX_focus_generic_manpower",
    "army":     "GFX_focus_generic_manpower",
    "rearm":    "GFX_focus_generic_military_mission",
    "military": "GFX_focus_generic_military_mission",
    "tank":     "GFX_focus_generic_army_tank",
    "armor":    "GFX_focus_generic_army_tank",
    "artillery":"GFX_focus_generic_army_artillery",
    "motorized":"GFX_focus_generic_army_motorized",
    "air":      "GFX_focus_generic_air_fighter",
    "fighter":  "GFX_focus_generic_air_fighter",
    "bomber":   "GFX_focus_generic_air_bomber",
    "navy":     "GFX_focus_generic_navy_cruiser",
    "naval":    "GFX_focus_generic_navy_cruiser",
    "submarine":"GFX_focus_generic_navy_submarine",
    "carrier":  "GFX_focus_generic_navy_carrier",
    "battleship":"GFX_focus_generic_navy_battleship",
    "political":"GFX_focus_generic_political_support",
    "fascism":  "GFX_focus_generic_political_fascism",
    "communism":"GFX_focus_generic_political_communism",
    "democracy":"GFX_focus_generic_political_democracy",
    "alliance": "GFX_focus_generic_alliance",
    "annex":    "GFX_focus_generic_annexation",
    "trade":    "GFX_focus_generic_trade",
    "research": "GFX_focus_generic_research",
    "radar":    "GFX_focus_generic_radar",
    "nuclear":  "GFX_focus_generic_nuclear",
    "rocket":   "GFX_focus_generic_rocket",
    "oil":      "GFX_focus_generic_oil",
    "steel":    "GFX_focus_generic_steel",
    "rubber":   "GFX_focus_generic_rubber",
    "fort":     "GFX_focus_generic_fortification",
    "defense":  "GFX_focus_generic_home_defense",
    "propaganda":"GFX_focus_generic_war_propaganda",
    "pp":       "GFX_focus_generic_pp_unity_bonus",
    "unity":    "GFX_focus_generic_pp_unity_bonus",
    "diplo":    "GFX_focus_generic_diplomatic_support",
    "support":  "GFX_focus_generic_diplomatic_support",
    "secret":   "GFX_focus_generic_secret_weapon",
}

_SKIP_WORDS = {"generic", "gfx", "focus", "1", "2", "3"}

def learn_icon_hints(hoi4_path):
    """Learn word/bigram→icon AND build focus_text→icon index from game data."""
    from collections import Counter, defaultdict
    word_icon = defaultdict(Counter)

    # focus_id → icon
    focus_icons = {}
    for f in (hoi4_path / "common/national_focus").glob("*.txt"):
        text = f.read_text(encoding="utf-8-sig", errors="ignore")
        for m in re.finditer(
            r'focus\s*=\s*\{[^{}]*?id\s*=\s*(\S+)[^{}]*?icon\s*=\s*(GFX_focus_generic_\S+)',
            text, re.DOTALL
        ):
            fid, icon = m.group(1), m.group(2)
            focus_icons[fid.lower()] = icon
            words = [w for w in fid.lower().split("_")[1:] if w and w not in _SKIP_WORDS]
            for word in words:
                word_icon[word][icon] += 1
            for i in range(len(words) - 1):
                word_icon[f"{words[i]}_{words[i+1]}"][icon] += 1

    # focus_id → localisation word set (for similarity matching)
    focus_loc_words = {}
    loc_dir = hoi4_path / "localisation" / "english"
    if not loc_dir.exists():
        loc_dir = hoi4_path / "localisation"
    for f in loc_dir.rglob("*.yml"):
        try:
            text = f.read_text(encoding="utf-8-sig", errors="ignore")
        except Exception:
            continue
        for m in re.finditer(r'^\s*(\w+):0\s+"([^"]+)"', text, re.MULTILINE):
            key = m.group(1).lower()
            if key in focus_icons:
                words = frozenset(
                    w.lower() for w in re.findall(r'\b[a-zA-Z]{4,}\b', m.group(2))
                    if w.lower() not in _SKIP_WORDS
                )
                if words:
                    focus_loc_words[key] = words
                    for word in words:
                        word_icon[word][focus_icons[key]] += 1

    word_hints = {w: c.most_common(1)[0][0] for w, c in word_icon.items()}
    return word_hints, focus_icons, focus_loc_words

_icon_hints = None
_focus_icons = {}
_focus_loc_words = {}
_mod_localisation = {}

def get_icon_hints():
    global _icon_hints, _focus_icons, _focus_loc_words
    if _icon_hints is None:
        cache = _load_cache()
        if cache and "icon_hints" in cache:
            _icon_hints = cache["icon_hints"]
            _focus_icons = cache.get("focus_icons", {})
            _focus_loc_words = {k: frozenset(v) for k, v in cache.get("focus_loc_words", {}).items()}
        else:
            hoi4 = find_hoi4_path()
            if hoi4:
                _icon_hints, _focus_icons, _focus_loc_words = learn_icon_hints(hoi4)
                c = _load_cache() or {}
                c.update({
                    "icon_hints": _icon_hints,
                    "focus_icons": _focus_icons,
                    "focus_loc_words": {k: list(v) for k, v in _focus_loc_words.items()},
                })
                _save_cache(c)
            else:
                _icon_hints, _focus_icons, _focus_loc_words = ICON_HINTS_FALLBACK, {}, {}
    return _icon_hints


def guess_icon(focus_id):
    hints = get_icon_hints()
    # Jaccard similarity against game focus localisations
    loc_text = _mod_localisation.get(focus_id, "")
    if loc_text and _focus_loc_words:
        query = frozenset(
            w.lower() for w in re.findall(r'\b[a-zA-Z]{4,}\b', loc_text)
            if w.lower() not in _SKIP_WORDS
        )
        if query:
            best_score, best_icon = 0.0, None
            for fid, fwords in _focus_loc_words.items():
                score = len(query & fwords) / len(query | fwords)
                if score > best_score:
                    best_score, best_icon = score, _focus_icons[fid]
            if best_score >= 0.2:
                return best_icon
    # Bigrams from ID end
    words = [w for w in focus_id.lower().split("_")[1:] if w not in _SKIP_WORDS]
    for i in range(len(words) - 1, 0, -1):
        if f"{words[i-1]}_{words[i]}" in hints:
            return hints[f"{words[i-1]}_{words[i]}"]
    for word in reversed(words):
        if word in hints:
            return hints[word]
    return "GFX_focus_generic_political_support"


def auto_layout_focuses(focuses):
    """Assign x/y to focuses that omit them, based on prereq depth + subtree centering."""
    from collections import defaultdict

    prereq_map = {}
    for f in focuses:
        fid = f.get("id")
        if not fid:
            continue
        # Support both prereq (AND) and prereq_or (OR) — combine all for layout purposes
        p = f.get("prereq")
        p_or = f.get("prereq_or")
        all_prereqs = (p if isinstance(p, list) else ([p] if p else [])) + \
                      (p_or if isinstance(p_or, list) else ([p_or] if p_or else []))
        prereq_map[fid] = all_prereqs

    # Spanning tree: primary parent = first valid prereq
    children = defaultdict(list)
    roots = []
    for fid in prereq_map:
        parents = [p for p in prereq_map[fid] if p in prereq_map]
        if parents:
            children[parents[0]].append(fid)
        else:
            roots.append(fid)

    # y = longest path from root
    y_cache = {}
    def get_y(fid, seen=frozenset()):
        if fid in y_cache:
            return y_cache[fid]
        parents = [p for p in prereq_map.get(fid, []) if p in prereq_map and p not in seen]
        y = max((get_y(p, seen | {fid}) + 1 for p in parents), default=0)
        y_cache[fid] = y
        return y
    for fid in prereq_map:
        get_y(fid)

    # Fixed focuses (explicit x or rel_pos) seed the x_map
    x_map = {}
    for f in focuses:
        fid = f.get("id")
        if fid and ("x" in f or "rel_pos" in f):
            x_map[fid] = f.get("x", 0)

    # Post-order: leaves get sequential slots, parents center over children
    counter = [0]
    fixed_ids = {f.get("id") for f in focuses if "x" in f or "rel_pos" in f}
    def assign_x(fid):
        kids = [k for k in children.get(fid, []) if k not in x_map]
        if fid in x_map:
            # Fixed: advance counter past it, still process children
            counter[0] = max(counter[0], x_map[fid] + 2)
            for kid in kids:
                assign_x(kid)
            return
        if not kids:
            x_map[fid] = counter[0]
            counter[0] += 2
        else:
            for kid in kids:
                assign_x(kid)
            xs = [x_map[k] for k in children.get(fid, []) if k in x_map]
            if xs:
                center = (min(xs) + max(xs)) // 2
                x_map[fid] = center + (center % 2)
            else:
                x_map[fid] = counter[0]; counter[0] += 2

    # Fixed roots first (sorted by x), then auto roots
    roots_sorted = sorted(roots, key=lambda fid: x_map.get(fid, float('inf')))
    for root in roots_sorted:
        assign_x(root)

    # Post-process: reposition multi-prereq nodes + their spanning-tree descendants
    multi_prereq = {fid for fid in prereq_map
                    if len([p for p in prereq_map[fid] if p in prereq_map]) > 1}
    # Propagate: find all spanning-tree descendants of multi-prereq nodes
    affected = set(multi_prereq)
    changed = True
    while changed:
        changed = False
        for fid in prereq_map:
            if fid not in affected:
                primary = next((p for p in prereq_map[fid] if p in prereq_map), None)
                if primary in affected:
                    affected.add(fid); changed = True
    # Reposition in topological order (y ascending)
    for fid in sorted(affected, key=lambda f: y_cache.get(f, 0)):
        if fid in fixed_ids:
            continue
        parents = [p for p in prereq_map[fid] if p in x_map]
        if parents:
            ideal = sum(x_map[p] for p in parents) // len(parents)
            x_map[fid] = ideal + (ideal % 2)

    # Apply
    for f in focuses:
        fid = f.get("id")
        if fid and fid in x_map and "x" not in f and "rel_pos" not in f:
            f["x"] = x_map[fid]
            f["y"] = y_cache.get(fid, 0)

    return focuses

def expand_shorthands(data):
    """Expand YAML shorthands to full Clausewitz equivalents."""
    if isinstance(data, list):
        return [expand_shorthands(i) for i in data]
    if not isinstance(data, dict):
        return data

    out = {}
    # Auto-assign focus icon from ID if missing
    if "id" in data and "icon" not in data and ("x" in data or "y" in data or "rel_pos" in data):
        out["icon"] = guess_icon(str(data["id"]))
    for k, v in data.items():
        # Auto-layout focus list before expanding individual items
        if k == "focus" and isinstance(v, list) and v and isinstance(v[0], dict) and "id" in v[0]:
            v = auto_layout_focuses([dict(f) for f in v])
        # prereq: X or [A, B]  →  prerequisite: { focus: X } / { focus: A focus: B } (AND)
        # prereq_or: [A, B]   →  prerequisite: { focus: A } prerequisite: { focus: B } (OR)
        if k == "prereq":
            if isinstance(v, list):
                # List = AND (all required in one block)
                out["prerequisite"] = {f"focus": v[0]} if len(v) == 1 else {"focus": v}
            else:
                out["prerequisite"] = {"focus": v}
        elif k == "prereq_or":
            # OR: multiple prerequisite blocks
            items = v if isinstance(v, list) else [v]
            out["prerequisite"] = [{"focus": f} for f in items]
        # ai_will_do: N  →  ai_will_do: { factor: N }
        # Calculation: result = factor * modifier1.factor * modifier2.factor * ...
        # factor: 0 = AI never picks this; factor: 1 with modifiers = conditional weight
        # if: [{cond: val, mult: N}]  →  modifier: { factor: N, cond: val }
        elif k == "ai_will_do":
            if isinstance(v, (int, float)):
                out["ai_will_do"] = {"factor": v}
            elif isinstance(v, dict) and "factor" in v:
                modifiers = []
                base = {"factor": v["factor"]}
                for mk, mv in v.items():
                    if mk == "factor":
                        continue
                    # Shorthand: if: {cond: val, mult: N} → modifier: { factor: N, cond: val }
                    if mk == "if" and isinstance(mv, list):
                        for item in mv:
                            mod = {"factor": item.pop("mult", 1)}
                            mod.update(item)
                            modifiers.append(mod)
                    elif mk == "if" and isinstance(mv, dict):
                        mod = {"factor": mv.pop("mult", 1)}
                        mod.update(mv)
                        modifiers.append(mod)
                result = dict(base)
                if modifiers:
                    result["modifier"] = modifiers
                out["ai_will_do"] = expand_shorthands(result)
            else:
                out["ai_will_do"] = expand_shorthands(v)
        elif k == "reward":
            out["completion_reward"] = expand_shorthands(v)
        # rel_pos: X  →  relative_position_id: X
        elif k == "rel_pos":
            out["relative_position_id"] = v
        # hidden: {...}  →  hidden_effect: {...}
        # NOTE: Use hidden_effect for effects you don't want shown in the event log
        # owner vs controller: owner = who owns the state (even if occupied), controller = who controls it now
        # set_variable: overwrites value; add_to_variable: adds to existing value (use clamp_variable after)
        # save_event_target_as: must be in same scope as FROM/ROOT when referenced later
        # limit: goes INSIDE every_state/every_country blocks, not outside
        # modifier (tech): country-level bonus; equipment_bonus: applies to equipment stats
        # on_action timing: on_war_won fires when war ends, on_capitulation when country capitulates
        # set_country_flag scope: fires on the CURRENT scope's country, use ROOT/FROM to target others
        elif k == "hidden":
            out["hidden_effect"] = expand_shorthands(v)
        # timed_idea: {idea: X, days: N}  →  add_ideas + remove_ideas with days_remove
        elif k == "timed_idea" and isinstance(v, dict):
            idea = v["idea"]
            days = v.get("days", 30)
            out["add_ideas"] = idea
            out["if"] = {"limit": {"NOT": {"has_idea": idea}},
                         "add_ideas": idea}
            # days_remove is set on the idea itself; emit a comment-style key
            out["_timed_idea_note"] = f"Set days_remove = {days} on idea '{idea}' definition"
        # division_template regiment/support shorthand
        # regiments: [{infantry: 3}, {artillery: 1}]  →  regiment blocks
        elif k == "regiments" and isinstance(v, list):
            out["regiment"] = [{"type": list(r.keys())[0], "column": i % 5, "row": i // 5}
                               for i, r in enumerate(v) for _ in range(list(r.values())[0])]
        elif k == "support_companies" and isinstance(v, list):
            out["support"] = [{"type": list(s.keys())[0], "column": i, "row": 0}
                              for i, s in enumerate(v)]
            out["hidden_effect"] = expand_shorthands(v)
        # add_state_building: {state: X, type: T, level: N, instant: true}
        # → state_id = { add_building_construction = { type = T level = N instant_build = yes } }
        elif k == "add_state_building" and isinstance(v, dict):
            sid = resolve_state(v["state"]) if "state" in v else v.get("state_id")
            payload = expand_shorthands({"add_building_construction": {
                "type": v["type"], "level": v.get("level", 1),
                "instant_build": "yes" if v.get("instant", True) else "no"
            }})
            out[sid] = {**out[sid], **payload} if sid in out and isinstance(out.get(sid), dict) else payload
        elif k == "add_state_manpower" and isinstance(v, dict):
            sid = resolve_state(v["state"]) if "state" in v else v.get("state_id")
            payload = {"add_manpower": v["value"]}
            out[sid] = {**out[sid], **payload} if sid in out and isinstance(out.get(sid), dict) else payload
        # sprites: [...]  →  spriteTypes: { spriteType: [...] }
        elif k == "sprites":
            out["spriteTypes"] = {"spriteType": expand_shorthands(v)}
        # set_tech: [tech1, tech2]  →  set_technology: { tech1: 1, tech2: 1 }
        elif k == "set_tech":
            techs = v if isinstance(v, list) else [v]
            out["set_technology"] = {t: 1 for t in techs}
        # set_ruling_party: X  →  set_politics: { ruling_party: X, elections_allowed: no, election_frequency: 48 }
        elif k == "set_ruling_party":
            out["set_politics"] = {"ruling_party": v, "elections_allowed": "no", "election_frequency": 48}
        # add_pop: { fascism: 0.1 }  →  add_popularity: { ideology: fascism, popularity: 0.1 }
        elif k == "add_pop" and isinstance(v, dict):
            for ideology, pop in v.items():
                out.setdefault("add_popularity", [])
                if not isinstance(out["add_popularity"], list):
                    out["add_popularity"] = [out["add_popularity"]]
                out["add_popularity"].append({"ideology": ideology, "popularity": pop})
        # color without color_ui  →  duplicate color as color_ui
        elif k == "color" and "color_ui" not in data:
            out["color"] = v
            out["color_ui"] = v
        else:
            out[k] = expand_shorthands(v)
    return out


# ── Generators ───────────────────────────────────────────────

def gen_descriptor(mod_dir, info, **kw):
    info = dict(info)
    info.setdefault("supported_version", "*")
    lines = []
    for k, v in info.items():
        if k == "tags":
            inner = "\n".join(f'\t"{t}"' for t in v)
            lines.append(f"tags = {{\n{inner}\n}}")
        else:
            lines.append(f'{k} = "{v}"')
    lines.append(f'path = "mod/{mod_dir.name}"')
    content = "\n".join(lines) + "\n"
    write(mod_dir / "descriptor.mod", content, **kw)
    write(mod_dir.parent / f"{mod_dir.name}.mod", content, **kw)


def gen_section(mod_dir, entries, subdir, ext="txt", **kw):
    if subdir == "events":
        entries = expand_events(entries)
    for entry in entries:
        filename = entry.get("_file", "generated")
        parts = []
        namespace = entry.get("_namespace", filename)
        has_event = any(k in entry for k in ("country_event", "news_event", "state_event"))
        if has_event:
            parts.append(f"add_namespace = {namespace}\n")
        if "_category" in entry:
            cat = entry["_category"]
            raw = {k: v for k, v in entry.items() if not k.startswith("_")}
            data = expand_shorthands(resolve_game_refs({"ideas": {cat: raw}}))
        elif "_wrap" in entry:
            wrap = entry["_wrap"]
            raw = {k: v for k, v in entry.items() if not k.startswith("_")}
            data = expand_shorthands(resolve_game_refs({wrap: raw}))
        else:
            data = expand_shorthands(resolve_game_refs({k: v for k, v in entry.items() if not k.startswith("_")}))
        if data:
            parts.append(to_clausewitz(data))
        write(mod_dir / subdir / f"{filename}.{ext}", "\n".join(parts) + "\n", **kw)


def gen_localisation(mod_dir, loc, **kw):
    if loc and isinstance(next(iter(loc.values())), dict):
        # Multi-language: fill missing keys from English as fallback
        english = loc.get("english", {})
        for lang, entries in loc.items():
            merged = {**english, **entries} if lang != "english" else entries
            lines = [f"l_{lang}:"] + [f' {k}:0 "{v}"' for k, v in merged.items()]
            write(mod_dir / "localisation" / f"mod_l_{lang}.yml", "\n".join(lines) + "\n", **kw)
    else:
        lines = ["l_english:"] + [f' {k}:0 "{v}"' for k, v in loc.items()]
        write(mod_dir / "localisation" / "mod_l_english.yml", "\n".join(lines) + "\n", **kw)


# ── Validation ───────────────────────────────────────────────

_hoi4_path = None

def find_hoi4_path():
    global _hoi4_path
    if _hoi4_path is not None:
        return _hoi4_path
    candidates = [
        # Windows Steam (native)
        "C:/Program Files (x86)/Steam/steamapps/common/Hearts of Iron IV",
        "C:/Program Files/Steam/steamapps/common/Hearts of Iron IV",
        *(f"{d}:/Steam/steamapps/common/Hearts of Iron IV" for d in "DEFGH"),
        *(f"{d}:/SteamLibrary/steamapps/common/Hearts of Iron IV" for d in "DEFGH"),
        *(f"{d}:/steamapps/common/Hearts of Iron IV" for d in "DEFGH"),
        # WSL → Windows
        "/mnt/c/Program Files (x86)/Steam/steamapps/common/Hearts of Iron IV",
        "/mnt/c/Program Files/Steam/steamapps/common/Hearts of Iron IV",
        *(f"/mnt/{d.lower()}/Steam/steamapps/common/Hearts of Iron IV" for d in "DEFGH"),
        *(f"/mnt/{d.lower()}/SteamLibrary/steamapps/common/Hearts of Iron IV" for d in "DEFGH"),
        # macOS
        "~/Library/Application Support/Steam/steamapps/common/Hearts of Iron IV",
        # Linux
        "~/.steam/steam/steamapps/common/Hearts of Iron IV",
        "~/.local/share/Steam/steamapps/common/Hearts of Iron IV",
    ]
    for c in candidates:
        p = Path(c).expanduser()
        if p.exists():
            _hoi4_path = p
            return _hoi4_path
    return None


def load_gfx_from_game(hoi4_path):
    gfx = set()
    for gfx_file in hoi4_path.glob("interface/*.gfx"):
        text = gfx_file.read_text(encoding="utf-8-sig", errors="ignore")
        gfx.update(re.findall(r'name\s*=\s*"?(GFX_\w+)"?', text))
    return gfx


def extract_mod_gfx(config):
    """Extract GFX keys defined in this mod's interface section."""
    gfx = set()
    for entry in config.get("interface", []):
        for sprite in entry.get("sprites", []):
            if "name" in sprite:
                gfx.add(sprite["name"])
        # Also handle raw spriteTypes
        st = entry.get("spriteTypes", {})
        for s in (st.get("spriteType") or []):
            if isinstance(s, dict) and "name" in s:
                gfx.add(s["name"])
    return gfx


def extract_mod_states(config):
    """Extract state name→id from this mod's history_states section."""
    state_map = {}
    for entry in config.get("history_states", []):
        state = entry.get("state", {})
        sid = state.get("id")
        name = state.get("name", "")
        if sid and name.startswith("STATE_"):
            # Try to get human name from localisation
            loc = config.get("localisation", {})
            if isinstance(next(iter(loc.values()), None), dict):
                loc = loc.get("english", {})
            human = loc.get(name, "").lower()
            if human:
                state_map[human] = int(sid)
    return state_map


def load_extra_mod_paths(mod_paths):
    """Scan additional mod directories for GFX keys, state IDs, localisation keys, traits, and ideologies."""
    extra_gfx = set()
    extra_states = {}
    extra_loc_keys = set()
    extra_traits = set()
    extra_ideologies = set()
    for path_str in (mod_paths or []):
        p = Path(path_str).expanduser()
        if not p.exists():
            warn(f"mod_path not found: {p}")
            continue
        # GFX from interface files
        for f in p.glob("interface/*.gfx"):
            extra_gfx.update(re.findall(r'name\s*=\s*"?(GFX_\w+)"?',
                f.read_text(encoding="utf-8-sig", errors="ignore")))
        # States from history/states
        for f in (p / "history/states").glob("*.txt") if (p / "history/states").exists() else []:
            text = f.read_text(encoding="utf-8-sig", errors="ignore")
            id_m  = re.search(r'\bid\s*=\s*(\d+)', text)
            key_m = re.search(r'\bname\s*=\s*"(STATE_\d+)"', text)
            if id_m and key_m:
                extra_states[key_m.group(1)] = int(id_m.group(1))
        # Localisation keys
        for f in p.glob("localisation/**/*.yml"):
            for m in re.finditer(r'^\s*(\S+):\d+\s+"', f.read_text(encoding="utf-8-sig", errors="ignore"), re.MULTILINE):
                extra_loc_keys.add(m.group(1))
        # Traits
        for trait_dir in ("common/country_leader", "common/unit_leader"):
            for f in (p / trait_dir).glob("*.txt") if (p / trait_dir).exists() else []:
                text = f.read_text(encoding="utf-8-sig", errors="ignore")
                for block in re.findall(r'leader_traits\s*=\s*\{(.+?)^\}', text, re.DOTALL | re.MULTILINE):
                    for m in re.finditer(r'^\t(\w+)\s*=\s*\{', block, re.MULTILINE):
                        extra_traits.add(m.group(1))
        # Ideologies
        for f in (p / "common/ideologies").glob("*.txt") if (p / "common/ideologies").exists() else []:
            text = f.read_text(encoding="utf-8-sig", errors="ignore")
            for m in re.finditer(r'^\s*(\w+)\s*=\s*\{', text, re.MULTILINE):
                extra_ideologies.add(m.group(1))
    return extra_gfx, extra_states, extra_loc_keys, extra_traits, extra_ideologies


def validate(config):
    # Known GFX: game + this mod's own sprites + extra mod paths
    known_gfx = set()
    hoi4_path = find_hoi4_path()
    if hoi4_path:
        known_gfx = load_gfx_from_game(hoi4_path)
    known_gfx |= extract_mod_gfx(config)
    extra_gfx, _, extra_loc_keys, extra_traits, extra_ideologies = load_extra_mod_paths(config.get("mod", {}).get("mod_paths", []))
    known_gfx |= extra_gfx

    # Merge sub-mod traits/ideologies into global sets for validation
    get_game_maps()
    if extra_traits and _trait_set is not None:
        _trait_set.update(extra_traits)
        if _country_leader_trait_set is not None:
            _country_leader_trait_set.update(extra_traits)
        if _unit_leader_trait_set is not None:
            _unit_leader_trait_set.update(extra_traits)
    if extra_ideologies and _ideology_set is not None:
        _ideology_set.update(extra_ideologies)

    loc = config.get("localisation", {})
    loc_keys = set()
    if loc and isinstance(next(iter(loc.values())), dict):
        for entries in loc.values():
            loc_keys.update(entries.keys())
    else:
        loc_keys.update(loc.keys())
    loc_keys |= extra_loc_keys

    focus_ids = []
    for entry in config.get("national_focus", []):
        for focus in (entry.get("focus_tree") or {}).get("focus", []):
            focus_ids.append(focus.get("id"))
            icon = focus.get("icon")
            if icon and known_gfx and icon not in known_gfx:
                warn(f"Unknown GFX key: {icon}")
    for d in {x for x in focus_ids if focus_ids.count(x) > 1}:
        warn(f"Duplicate focus id: {d}")

    # Collect event IDs referenced anywhere in the config (they need is_triggered_only)
    referenced_event_ids = set()
    def _collect_all_event_refs(d):
        if isinstance(d, list):
            for i in d: _collect_all_event_refs(i)
        elif isinstance(d, dict):
            for k, v in d.items():
                if k in ("country_event", "news_event", "state_event", "random_events"):
                    if isinstance(v, (str, int)):
                        referenced_event_ids.add(str(v))
                    elif isinstance(v, dict) and "id" in v:
                        referenced_event_ids.add(str(v["id"]))
                    else:
                        _collect_all_event_refs(v)
                else:
                    _collect_all_event_refs(v)
    _collect_all_event_refs(config)

    event_ids = []
    for entry in config.get("events", []):
        for etype in ("country_event", "news_event", "state_event"):
            for ev in (entry.get(etype) or []):
                event_ids.append(ev.get("id"))
                eid = str(ev.get("id", ""))
                if (not ev.get("is_triggered_only") and not ev.get("mean_time_to_happen")
                        and eid not in referenced_event_ids):
                    warn(f"Event '{eid}' has neither 'is_triggered_only' nor 'mean_time_to_happen' — it will never fire")
                for key in ("title", "desc"):
                    val = ev.get(key)
                    if val and val not in loc_keys:
                        warn(f"Missing localisation: {val}")
                for opt in (ev.get("option") or []):
                    name = opt.get("name")
                    if not name:
                        warn(f"Event '{ev.get('id')}' has an option without 'name' — localisation key required")
                    elif name not in loc_keys:
                        warn(f"Missing localisation: {name}")
    for d in {x for x in event_ids if event_ids.count(x) > 1}:
        warn(f"Duplicate event id: {d}")

    # Ideology / trait / tech_category validation (requires game data)
    get_game_maps()  # ensure globals loaded
    if _ideology_set or _trait_set or _tech_category_set:
        import difflib

        # Context-aware keys that indicate leader type
        COUNTRY_LEADER_KEYS = {"country_leader"}
        UNIT_LEADER_KEYS = {"field_marshal", "corps_commander", "navy_leader"}
        IDEOLOGY_KEYS = {"ideology", "ruling_party"}
        EFFECT_CTX_KEYS = {"completion_reward", "option", "immediate", "after", "hidden_effect"}

        def _check_recursive(data, ctx=None):
            if isinstance(data, list):
                for i in data: _check_recursive(i, ctx)
            elif isinstance(data, dict):
                for k, v in data.items():
                    new_ctx = ctx
                    if k in COUNTRY_LEADER_KEYS:
                        new_ctx = "country_leader"
                    elif k in UNIT_LEADER_KEYS:
                        new_ctx = "unit_leader"
                    elif k in EFFECT_CTX_KEYS:
                        new_ctx = k
                    elif k in ("regiment", "support"):
                        new_ctx = "regiment"
                    elif k in ("add_equipment_to_stockpile", "equipment"):
                        new_ctx = "equipment"

                    if k in IDEOLOGY_KEYS and isinstance(v, str) and _ideology_set and v not in _ideology_set:
                        close = difflib.get_close_matches(v, _ideology_set, n=3, cutoff=0.5)
                        warn(f"Unknown ideology: '{v}'" + (f" — did you mean: {close}?" if close else ""))
                    elif k == "traits" and isinstance(v, list):
                        valid = (_country_leader_trait_set if ctx == "country_leader"
                                 else _unit_leader_trait_set if ctx == "unit_leader"
                                 else _trait_set)
                        ctx_label = f" ({ctx})" if ctx else ""
                        for t in v:
                            if isinstance(t, str) and valid and t not in valid:
                                close = difflib.get_close_matches(t, valid, n=3, cutoff=0.5)
                                warn(f"Unknown trait{ctx_label}: '{t}'" + (f" — did you mean: {close}?" if close else ""))
                    elif k == "categories" and isinstance(v, list) and _tech_category_set:
                        for c in v:
                            if isinstance(c, str) and c not in _tech_category_set:
                                close = difflib.get_close_matches(c, _tech_category_set, n=3, cutoff=0.5)
                                warn(f"Unknown tech category: '{c}'" + (f" — did you mean: {close}?" if close else ""))
                    elif k in ("add_building_construction", "set_building_level") and _building_max:
                        btype = v.get("type") if isinstance(v, dict) else None
                        level = v.get("level") if isinstance(v, dict) else (v if isinstance(v, int) else None)
                        if btype and level and btype in _building_max and level > _building_max[btype]:
                            warn(f"Building '{btype}' level {level} exceeds max {_building_max[btype]}")
                    elif k in _building_max and isinstance(v, int) and v > _building_max[k]:
                        warn(f"Building '{k}' level {v} exceeds max {_building_max[k]}")
                    elif k == "resources" and isinstance(v, dict) and _resource_set:
                        for rk in v:
                            if rk not in _resource_set:
                                import difflib
                                close = difflib.get_close_matches(rk, _resource_set, n=3, cutoff=0.4)
                                warn(f"Unknown resource: '{rk}'" + (f" — did you mean: {close}?" if close else f" — valid: {sorted(_resource_set)}"))
                    elif k in ("add_resource",) and isinstance(v, dict) and _resource_set:
                        rtype = v.get("type")
                        if rtype and rtype not in _resource_set:
                            import difflib
                            close = difflib.get_close_matches(rtype, _resource_set, n=3, cutoff=0.4)
                            warn(f"Unknown resource: '{rtype}'" + (f" — did you mean: {close}?" if close else f" — valid: {sorted(_resource_set)}"))
                    elif k == "type" and isinstance(v, str) and ctx == "regiment" and _sub_unit_set and v not in _sub_unit_set:
                        import difflib
                        close = difflib.get_close_matches(v, _sub_unit_set, n=3, cutoff=0.5)
                        warn(f"Unknown unit type: '{v}'" + (f" — did you mean: {close}?" if close else ""))
                    elif k == "type" and isinstance(v, str) and ctx in ("equipment", "add_equipment_to_stockpile") and _equipment_type_set and v not in _equipment_type_set:
                        import difflib
                        close = difflib.get_close_matches(v, _equipment_type_set, n=3, cutoff=0.5)
                        warn(f"Unknown equipment type: '{v}'" + (f" — did you mean: {close}?" if close else ""))
                    elif k == "ai_will_do" and isinstance(v, dict) and v.get("factor") == 0:
                        warn(f"ai_will_do factor: 0 — AI will never pick this (use factor: 1 with modifiers instead)")
                    elif k == "modifier" and isinstance(v, dict) and ctx in EFFECT_CTX_KEYS:
                        warn(f"'modifier' block in effect context ('{ctx}') does nothing — use 'add_modifier' or 'add_ideas' instead")
                        _check_recursive(v, new_ctx)
                    elif k == "add_core_of" and isinstance(v, (int, float)):
                        warn(f"'add_core_of' takes a country TAG (e.g. GER), not a number — did you mean 'add_core = {v}'?")
                    elif k == "add_core" and isinstance(v, str) and re.match(r'^[A-Z]{2,3}$', v):
                        warn(f"'add_core' takes a state ID (number), not a TAG — did you mean 'add_core_of = {v}'?")
                    elif k == "set_technology" and isinstance(v, dict) and "type" in v:
                        warn(f"'set_technology' does not use a 'type' key — use '{{ tech_name: 1 }}' directly, e.g. set_technology: {{ {v.get('type')}: 1 }}")
                    elif k == "add_tech_bonus" and isinstance(v, dict) and "category" not in v:
                        warn(f"'add_tech_bonus' missing 'category' — it will not work without specifying a tech category")
                    elif k == "set_politics" and isinstance(v, dict):
                        for req in ("ruling_party", "elections_allowed", "election_frequency"):
                            if req not in v:
                                warn(f"'set_politics' missing '{req}' — all three fields are required")
                        _check_recursive(v, new_ctx)
                    elif k == "add_popularity" and isinstance(v, dict):
                        for req in ("ideology", "popularity"):
                            if req not in v:
                                warn(f"'add_popularity' missing '{req}' — use add_popularity: {{ ideology: X, popularity: 0.1 }}")
                        _check_recursive(v, new_ctx)
                    elif k == "create_wargoal" and isinstance(v, dict):
                        if "type" not in v:
                            warn(f"'create_wargoal' missing 'type'")
                        elif _wargoal_type_set and v["type"] not in _wargoal_type_set:
                            import difflib
                            close = difflib.get_close_matches(v["type"], _wargoal_type_set, n=3, cutoff=0.4)
                            warn(f"Unknown wargoal type: '{v['type']}'" + (f" — did you mean: {close}?" if close else f" — valid: {sorted(_wargoal_type_set)}"))
                        if "target" not in v:
                            warn(f"'create_wargoal' missing 'target' (country TAG)")
                        _check_recursive(v, new_ctx)
                    elif k == "equipment_bonus" and isinstance(v, dict):
                        for eq_key, eq_val in v.items():
                            if isinstance(eq_val, dict) and "instant" not in eq_val:
                                warn(f"'equipment_bonus.{eq_key}' missing 'instant: yes' — bonus only applies to newly produced equipment, not existing stockpile")
                        _check_recursive(v, new_ctx)
                    elif k == "modifier" and isinstance(v, dict) and ctx not in EFFECT_CTX_KEYS and _modifier_name_set:
                        for mk in v:
                            if mk not in _modifier_name_set:
                                import difflib
                                close = difflib.get_close_matches(mk, _modifier_name_set, n=3, cutoff=0.5)
                                warn(f"Unknown modifier: '{mk}'" + (f" — did you mean: {close}?" if close else ""))
                        _check_recursive(v, new_ctx)
                    elif k == "random_list" and isinstance(v, dict):
                        for weight, _ in v.items():
                            try:
                                float(str(weight))
                            except ValueError:
                                warn(f"random_list key '{weight}' is not a number (weights must be numeric)")
                        _check_recursive(v, new_ctx)
                    elif k in ("completion_reward", "option", "immediate", "after", "hidden_effect") and isinstance(v, (dict, list)):
                        # Check for trigger-only keywords used as effects
                        TRIGGER_ONLY = {"has_war", "is_major", "tag", "has_government", "has_idea",
                                        "has_tech", "has_stability", "has_war_support", "num_of_factories",
                                        "is_ai", "has_full_control_of_state", "has_capitulated"}
                        # Check for effect-only keywords used as triggers (in trigger/limit blocks)
                        EFFECT_ONLY = {"add_political_power", "add_stability", "add_war_support",
                                       "add_manpower", "add_equipment_to_stockpile", "set_politics",
                                       "add_ideas", "remove_ideas", "start_war", "white_peace"}
                        def _find_triggers(d, ctx_key):
                            if isinstance(d, list):
                                for i in d: _find_triggers(i, ctx_key)
                            elif isinstance(d, dict):
                                for dk, dv in d.items():
                                    if dk in TRIGGER_ONLY:
                                        warn(f"'{dk}' is a trigger, not an effect — found in '{ctx_key}' block")
                                    elif dk not in ("limit", "trigger"):
                                        _find_triggers(dv, ctx_key)
                        def _find_effects_in_triggers(d, ctx_key):
                            if isinstance(d, list):
                                for i in d: _find_effects_in_triggers(i, ctx_key)
                            elif isinstance(d, dict):
                                for dk, dv in d.items():
                                    if dk in EFFECT_ONLY:
                                        warn(f"'{dk}' is an effect, not a trigger — found in '{ctx_key}' block")
                                    else:
                                        _find_effects_in_triggers(dv, ctx_key)
                        _find_triggers(v, k)
                        # Check trigger/limit sub-blocks for effects
                        def _scan_for_trigger_blocks(d):
                            if isinstance(d, list):
                                for i in d: _scan_for_trigger_blocks(i)
                            elif isinstance(d, dict):
                                for sub_k in ("trigger", "limit"):
                                    if sub_k in d:
                                        _find_effects_in_triggers(d[sub_k], sub_k)
                                for dv in d.values():
                                    if isinstance(dv, (dict, list)):
                                        _scan_for_trigger_blocks(dv)
                        _scan_for_trigger_blocks(v)
                        _check_recursive(v, new_ctx)
                    # news_event fired from effect context → likely should be country_event
                    elif k == "news_event" and ctx in EFFECT_CTX_KEYS:
                        warn(f"'news_event' fires for ALL countries — use 'country_event' if targeting specific countries only")
                        _check_recursive(v, new_ctx)
                    # add_to_variable without nearby clamp_variable
                    elif k == "add_to_variable" and isinstance(data, dict) and "clamp_variable" not in data:
                        warn(f"'add_to_variable' without 'clamp_variable' — variable may go negative or overflow")
                        _check_recursive(v, new_ctx)
                    # set_country_flag scope note
                    elif k == "set_country_flag" and ctx in EFFECT_CTX_KEYS:
                        # Just recurse; scope is user's responsibility
                        _check_recursive(v, new_ctx)
                    else:
                        _check_recursive(v, new_ctx)
        _check_recursive(config)

    # Check remove_ideas against ideas with removal_cost = -1
    non_removable = set()
    for entry in config.get("ideas", []):
        if "_category" in entry:
            # _category style: idea defs are direct non-underscore keys
            for idea_name, idea_def in entry.items():
                if not idea_name.startswith("_") and isinstance(idea_def, dict):
                    if idea_def.get("removal_cost") == -1:
                        non_removable.add(idea_name)
        else:
            # Regular style: ideas: { category: { idea_name: {...} } }
            for cat_ideas in entry.values():
                if isinstance(cat_ideas, dict):
                    for idea_name, idea_def in cat_ideas.items():
                        if isinstance(idea_def, dict) and idea_def.get("removal_cost") == -1:
                            non_removable.add(idea_name)
    if non_removable:
        def _find_remove_ideas(data):
            if isinstance(data, list):
                for i in data: _find_remove_ideas(i)
            elif isinstance(data, dict):
                if "remove_ideas" in data:
                    targets = data["remove_ideas"]
                    if isinstance(targets, str): targets = [targets]
                    for t in (targets if isinstance(targets, list) else []):
                        if t in non_removable:
                            warn(f"'remove_ideas: {t}' — this idea has removal_cost: -1 (cannot be removed)")
                for v in data.values():
                    _find_remove_ideas(v)
        _find_remove_ideas(config)

    # Warn if 'character' (singular) used as top-level section (should be 'characters')
    if "character" in config:
        warn(f"Top-level key 'character' found — did you mean 'characters'?")

    # Technology: missing path or folder
    for entry in config.get("technologies", []):
        for tech_name, tech_def in entry.items():
            if tech_name.startswith("_") or not isinstance(tech_def, dict):
                continue
            if "path" not in tech_def and "folder" not in tech_def and "on_research_complete" not in tech_def:
                warn(f"Technology '{tech_name}' has no 'path' or 'folder' — it will not appear in the tech tree")

    # history_countries: capital should be a province ID (typically > 1000), not a state ID
    for entry in config.get("history_countries", []):
        cap = entry.get("capital") or (entry.get("history") or {}).get("capital")
        if cap and isinstance(cap, int) and cap < 1000:
            warn(f"'capital = {cap}' looks like a state ID — 'capital' takes a province ID (usually > 1000)")

    # load_oob: referenced file must exist in history_units section
    oob_files = {entry.get("_file") for entry in config.get("history_units", [])}
    def _find_load_oob(d):
        if isinstance(d, list):
            for i in d: _find_load_oob(i)
        elif isinstance(d, dict):
            if "load_oob" in d:
                ref = d["load_oob"]
                if isinstance(ref, str) and ref not in oob_files:
                    warn(f"'load_oob = {ref}' — no matching history_units entry with _file: {ref}")
            for v in d.values():
                _find_load_oob(v)
    _find_load_oob(config)


# ── Section map ──────────────────────────────────────────────

SECTIONS = {
    "national_focus":        ("common/national_focus",              "txt"),
    "events":                ("events",                             "txt"),
    "ideas":                 ("common/ideas",                       "txt"),
    "decisions":             ("common/decisions",                   "txt"),
    "decisions_categories":  ("common/decisions/categories",        "txt"),
    "technologies":          ("common/technologies",                "txt"),
    "on_actions":            ("common/on_actions",                  "txt"),
    "characters":            ("common/characters",                  "txt"),
    "portraits":             ("common/portraits",                   "txt"),
    "country_leader":        ("common/country_leader",              "txt"),
    "unit_leader":           ("common/unit_leader",                 "txt"),
    "scripted_triggers":     ("common/scripted_triggers",           "txt"),
    "scripted_effects":      ("common/scripted_effects",            "txt"),
    "scripted_localisation": ("common/scripted_localisation",       "txt"),
    "scripted_gui":          ("common/scripted_gui",                "txt"),
    "opinion_modifiers":     ("common/opinion_modifiers",           "txt"),
    "dynamic_modifiers":     ("common/dynamic_modifiers",           "txt"),
    "modifiers":             ("common/modifiers",                   "txt"),
    "wargoals":              ("common/wargoals",                    "txt"),
    "bookmarks":             ("common/bookmarks",                   "txt"),
    "country_tags":          ("common/country_tags",                "txt"),
    "country_colors":        ("common/countries",                   "txt"),
    "cosmetic_tags":         ("common/cosmetic_tags",               "txt"),
    "autonomy":              ("common/autonomy",                    "txt"),
    "game_rules":            ("common/game_rules",                  "txt"),
    "peace_conference":      ("common/peace_conference",            "txt"),
    "ai_strategy":           ("common/ai_strategy",                 "txt"),
    "ai_focuses":            ("common/ai_focuses",                  "txt"),
    "ai_peace":              ("common/ai_peace",                    "txt"),
    "ai_templates":          ("common/ai_templates",                "txt"),
    "ai_equipment_designs":  ("common/ai_equipment_designs",        "txt"),
    "ai_strategy_plans":     ("common/ai_strategy_plans",           "txt"),
    "equipment":             ("common/units/equipment",             "txt"),
    "units":                 ("common/units",                       "txt"),
    "buildings":             ("common/buildings",                   "txt"),
    "resources":             ("common/resources",                   "txt"),
    "terrain":               ("common/terrain",                     "txt"),
    "state_category":        ("common/state_category",              "txt"),
    "named_colors":          ("common/named_colors",                "txt"),
    "medals":                ("common/medals",                      "txt"),
    "map_modes":             ("common/map_modes",                   "txt"),
    "strategic_regions":     ("map/strategicregions",               "txt"),
    "special_projects":      ("common/special_projects",            "txt"),
    "timed_activities":      ("common/timed_activities",            "txt"),
    "scripted_diplomatic_actions": ("common/scripted_diplomatic_actions", "txt"),
    "history_countries":     ("history/countries",                  "txt"),
    "history_states":        ("history/states",                     "txt"),
    "history_units":         ("history/units",                      "txt"),
    "interface":             ("interface",                          "gfx"),
    "music":                 ("music",                              "asset"),
}


# ── Config loading ───────────────────────────────────────────

def load_configs(yaml_files):
    merged = {}
    for f in yaml_files:
        config = yaml.safe_load(Path(f).read_text(encoding="utf-8"))
        for key, value in config.items():
            if key in merged and isinstance(value, list):
                merged[key].extend(value)
            elif key in merged and isinstance(value, dict):
                merged[key].update(value)
            else:
                merged[key] = value
    return merged


def preprocess(config):
    variables = config.get("vars", {})
    templates = config.get("templates", {})
    if variables:
        config = apply_vars(config, variables)
    if templates:
        config = apply_templates(config, templates)
    config = apply_conditions(config)
    return config


# ── Main generate ────────────────────────────────────────────

def generate(yaml_files, clean=False, dry_run=False, output_dir=Path("output"), do_zip=False):
    global _file_count, _warn_count
    _file_count = 0
    _warn_count = 0

    config = preprocess(load_configs(yaml_files))
    info = config.get("mod", {})
    mod_name = info.get("name", "my_mod").lower().replace(" ", "_")
    mod_dir = output_dir / mod_name

    if clean and mod_dir.exists() and not dry_run:
        shutil.rmtree(mod_dir)
        print(f"{Y}Cleaned:{X} {mod_dir}/")

    # Register mod's own states + sub-mod states for name resolution
    _extra_state_map.update(extract_mod_states(config))
    _, extra_states, _, _, _ = load_extra_mod_paths(info.get("mod_paths", []))
    _extra_state_map.update(extra_states)

    print(f"{B}Generating:{X} {info.get('name', mod_name)}")
    validate(config)

    # Set mod localisation for icon guessing
    loc = config.get("localisation", {})
    if loc and isinstance(next(iter(loc.values())), dict):
        _mod_localisation.update(loc.get("english", {}))
    else:
        _mod_localisation.update(loc)
    gen_descriptor(mod_dir, info, dry_run=dry_run)

    for section, (subdir, ext) in SECTIONS.items():
        if section in config:
            gen_section(mod_dir, config[section], subdir, ext=ext, dry_run=dry_run)

    if "localisation" in config:
        gen_localisation(mod_dir, config["localisation"], dry_run=dry_run)

    if do_zip and not dry_run:
        zip_path = output_dir / f"{mod_name}.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for f in mod_dir.rglob("*"):
                zf.write(f, f.relative_to(output_dir))
            mod_file = output_dir / f"{mod_name}.mod"
            if mod_file.exists():
                zf.write(mod_file, mod_file.name)
        print(f"{G}Zipped:{X} {zip_path}")

    warns = f"  {Y}{_warn_count} warnings{X}" if _warn_count else ""
    print(f"\nDone → {mod_dir}/  ({G}{_file_count} files{X}{warns})\n")


# ── Import (Clausewitz → YAML) ───────────────────────────────

def do_import(path_str):
    path = Path(path_str)
    if path.is_file():
        files = [path]
    else:
        files = list(path.rglob("*.txt")) + list(path.rglob("*.gfx")) + list(path.rglob("*.asset"))

    result = {}
    for f in files:
        try:
            parsed = parse_clausewitz(f.read_text(encoding="utf-8-sig", errors="ignore"))
            if parsed:
                result[f.stem] = parsed
                print(f"  {G}imported:{X} {f}")
        except Exception as e:
            print(f"  {R}skip:{X} {f} ({e})")

    out = Path("imported.yaml")
    out.write_text(yaml.dump(result, allow_unicode=True, sort_keys=False), encoding="utf-8")
    print(f"\n{G}Saved:{X} {out}")


# ── Init wizard ──────────────────────────────────────────────

def do_init():
    print(f"{B}hoi4yaml init{X} - New mod setup\n")
    name    = input("Mod name: ").strip() or "My Mod"
    version = input("Version [1.0.0]: ").strip() or "1.0.0"
    hoi4ver = input("Supported HoI4 version [*]: ").strip() or "*"
    tags    = input("Tags (comma separated) [Historical]: ").strip() or "Historical"
    tag_list = [t.strip() for t in tags.split(",")]

    scaffold = {
        "mod": {
            "name": name,
            "version": version,
            "supported_version": hoi4ver,
            "tags": tag_list,
        },
        "vars": {
            "MOD_TAG": name.upper().replace(" ", "_")[:3],
        },
        "localisation": {
            "english": {},
            "japanese": {},
        },
    }

    out = Path("mod.yaml")
    if out.exists():
        overwrite = input(f"{Y}mod.yaml already exists. Overwrite? [y/N]:{X} ").strip().lower()
        if overwrite != "y":
            print("Aborted.")
            return

    out.write_text(yaml.dump(scaffold, allow_unicode=True, sort_keys=False), encoding="utf-8")
    print(f"\n{G}Created:{X} mod.yaml")


# ── List sections ────────────────────────────────────────────

def do_list():
    print(f"{B}Supported sections:{X}\n")
    for section, (subdir, ext) in SECTIONS.items():
        print(f"  {G}{section:<25}{X} → {subdir}/*.{ext}")
    print(f"\n  {G}{'localisation':<25}{X} → localisation/mod_l_<lang>.yml")
    print(f"  {G}{'templates':<25}{X} → (used for _template inheritance)")
    print(f"  {G}{'vars':<25}{X} → (used for $VAR substitution)")
    print(f"\n{B}Shorthands:{X}\n")
    shorthands = [
        ("prereq: X",              "prerequisite: {{ focus: X }} (AND)"),
        ("prereq: [A, B]",         "prerequisite: {{ focus: A focus: B }} (AND, both required)"),
        ("prereq_or: [A, B]",      "prerequisite: {{ focus: A }} prerequisite: {{ focus: B }} (OR)"),
        ("reward:",                "completion_reward:"),
        ("rel_pos: X",             "relative_position_id: X"),
        ("hidden: {{...}}",        "hidden_effect: {{...}}"),
        ("ai_will_do: N",          "ai_will_do: {{ factor: N }}"),
        ("ai_will_do.if: [...]",   "modifier blocks with factor/conditions"),
        ("add_state_building:",    "state_id = {{ add_building_construction = {{...}} }}"),
        ("add_state_manpower:",    "state_id = {{ add_manpower = N }}"),
        ("regiments: [...]",       "regiment blocks with column/row auto-assigned"),
        ("support_companies: [...]","support blocks with column/row auto-assigned"),
        ("sprites: [...]",         "spriteTypes: {{ spriteType: [...] }}"),
        ("set_tech: [A, B]",       "set_technology: {{ A: 1, B: 1 }}"),
        ("set_ruling_party: X",    "set_politics: {{ ruling_party: X, elections_allowed: no, election_frequency: 48 }}"),
        ("add_pop: {{X: 0.1}}",    "add_popularity: {{ ideology: X, popularity: 0.1 }}"),
        ("_category: country",     "ideas: {{ country: {{...}} }}"),
        ("_wrap: characters",      "characters: {{...}}"),
        ("_template: X",           "inherit from templates.X"),
        ("_if: false",             "skip this entry"),
    ]
    for short, expanded in shorthands:
        print(f"  {G}{short:<30}{X} → {expanded}")
    print(f"\n{B}Common mistakes (validated):{X}\n")
    notes = [
        ("ideology/ruling_party",  "checked against game data"),
        ("traits",                 "checked per context: country_leader vs unit_leader"),
        ("categories (tech)",      "checked against tech categories from game files"),
        ("building levels",        "checked against state_max from game files"),
        ("resources",              "checked against game data (oil/aluminium/steel etc.)"),
        ("unit types",             "checked against sub_unit definitions from game files"),
        ("equipment types",        "checked against equipment definitions from game files"),
        ("modifier names",         "checked against 638 modifier names from game files"),
        ("wargoal types",          "checked against wargoal_types from game files"),
        ("effect in trigger block","has_war/is_major etc. in completion_reward → WARN"),
        ("trigger in effect block","add_stability etc. in trigger/limit → WARN"),
        ("modifier in effect ctx", "modifier: {{...}} in completion_reward does nothing → WARN"),
        ("set_technology type key","set_technology: {{type: X}} is wrong syntax → WARN"),
        ("add_tech_bonus category","missing category field → WARN"),
        ("set_politics fields",    "missing ruling_party/elections_allowed/election_frequency → WARN"),
        ("add_popularity fields",  "missing ideology/popularity → WARN"),
        ("create_wargoal fields",  "missing type/target → WARN"),
        ("equipment_bonus instant","missing instant: yes → only new production affected → WARN"),
        ("add_core_of vs add_core","add_core_of=TAG, add_core=state_id — reversed → WARN"),
        ("capital province ID",    "capital takes province ID not state ID → WARN"),
        ("load_oob reference",     "checked against history_units entries → WARN"),
        ("technology path/folder", "missing path or folder → won't appear in tech tree → WARN"),
        ("event fire condition",   "no is_triggered_only or mean_time_to_happen → WARN"),
        ("event option name",      "option without name key → WARN"),
        ("news_event in option",   "fires for ALL countries → WARN"),
        ("add_to_variable",        "without clamp_variable → WARN"),
        ("remove_ideas",           "on removal_cost: -1 ideas → WARN"),
        ("character (singular)",   "should be 'characters' → WARN"),
        ("ai_will_do: {{factor: 0}}","AI never picks this → WARN"),
        ("random_list non-numeric","weights must be numbers → WARN"),
        ("GFX keys",               "checked against game + mod sprite definitions"),
        ("localisation keys",      "missing loc keys for events/focuses/ideas → WARN"),
        ("duplicate IDs",          "focus IDs and event IDs checked for duplicates"),
    ]
    for key, note in notes:
        print(f"  {G}{key:<30}{X} {note}")


# ── Arg parsing & main ───────────────────────────────────────

def parse_args(args):
    flags = set()
    files = []
    output_dir = Path("output")
    i = 0
    while i < len(args):
        a = args[i]
        if a == "--output" and i + 1 < len(args):
            output_dir = Path(args[i + 1])
            i += 2
        elif a.startswith("--"):
            flags.add(a)
            i += 1
        else:
            files.append(a)
            i += 1
    return files or ["mod.yaml"], flags, output_dir


def main():
    args = sys.argv[1:]

    if not args or args[0] == "--list":
        do_list()
        return

    if args[0] == "--init":
        do_init()
        return

    if args[0] == "--import":
        if len(args) < 2:
            print(f"{R}Usage:{X} generate.py --import <file_or_dir>")
            return
        do_import(args[1])
        return

    if args[0] == "--list-states":
        import difflib
        query = args[1].lower() if len(args) > 1 else ""
        state_map, _, _ = get_game_maps()
        if query:
            exact = {n: sid for n, sid in state_map.items() if query in n}
            fuzzy = {n: state_map[n] for n in difflib.get_close_matches(query, state_map.keys(), n=10, cutoff=0.4)}
            results = {**exact, **fuzzy}
            if query.isdigit():
                qid = int(query)
                id_to_name = {v: k for k, v in state_map.items()}
                for sid in range(max(1, qid - 2), qid + 3):
                    if sid in id_to_name:
                        results[id_to_name[sid]] = sid
        else:
            results = dict(sorted(state_map.items(), key=lambda x: x[1])[:30])
        for name, sid in sorted(results.items(), key=lambda x: x[1]):
            print(f"  {sid:4}  {name}")
        return

    if args[0] == "--list-countries":
        query = args[1].lower() if len(args) > 1 else ""
        _, _, country_map = get_game_maps()
        results = {n: t for n, t in country_map.items() if not query or query in n or query in t.lower()}
        for name, tag in sorted(results.items(), key=lambda x: x[1]):
            print(f"  {tag}  {name}")
        return

    files, flags, output_dir = parse_args(args)

    if "--validate" in flags:
        config = preprocess(load_configs(files))
        validate(config)
        if _warn_count == 0:
            print(f"{G}No issues found.{X}")
        return

    kw = dict(
        clean=("--clean" in flags),
        dry_run=("--dry-run" in flags),
        output_dir=output_dir,
        do_zip=("--zip" in flags),
    )

    generate(files, **kw)

    if "--watch" in flags:
        print(f"{B}Watching for changes...{X} (Ctrl+C to stop)")
        mtimes = {f: Path(f).stat().st_mtime for f in files}
        while True:
            time.sleep(1)
            if any(Path(f).stat().st_mtime != mtimes[f] for f in files):
                mtimes = {f: Path(f).stat().st_mtime for f in files}
                print("Change detected, regenerating...")
                generate(files, **kw)


if __name__ == "__main__":
    main()
