import yaml
import re
from pathlib import Path

G = "\033[32m"; Y = "\033[33m"; R = "\033[31m"; B = "\033[36m"; X = "\033[0m"
HEADER = "# Generated by hoi4yaml - https://github.com/you/hoi4yaml\n\n"

_file_count = 0
_warn_count = 0


def write(path, content, dry_run=False, diff_only=False):
    global _file_count
    if dry_run:
        print(f"  {B}[dry-run]{X} {path}"); return
    full_content = HEADER + content
    if diff_only and path.exists() and path.read_text(encoding="utf-8") == full_content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    enc = "utf-8-sig" if path.suffix == ".yml" else "utf-8"
    path.write_text(full_content, encoding=enc)
    _file_count += 1
    print(f"  {G}+{X} {path}")


def warn(msg, line=None):
    global _warn_count
    _warn_count += 1
    loc = f"{Y}:{line}{X} " if line else ""
    print(f"  {Y}[WARN]{X} {loc}{msg}")


def apply_vars(data, variables):
    if isinstance(data, str):
        for k, v in variables.items():
            data = data.replace(f"${k}", str(v))
        return data
    if isinstance(data, dict):
        return {k: apply_vars(v, variables) for k, v in data.items()}
    if isinstance(data, list):
        return [apply_vars(i, variables) for i in data]
    return data


def apply_templates(data, templates):
    if isinstance(data, dict):
        if "_template" in data:
            base = templates.get(data["_template"], {}).copy()
            base.update({k: v for k, v in data.items() if k != "_template"})
            data = base
        return {k: apply_templates(v, templates) for k, v in data.items()}
    if isinstance(data, list):
        return [apply_templates(item, templates) for item in data]
    return data


def apply_conditions(data):
    if isinstance(data, dict):
        if data.get("_if") is False:
            return None
        return {k: apply_conditions(v) for k, v in data.items() if apply_conditions(v) is not None}
    if isinstance(data, list):
        return [i for i in (apply_conditions(x) for x in data) if i is not None]
    return data


class _LineDict(dict):
    __slots__ = ("_line",)


def _load_yaml_with_lines(text):
    class _Loader(yaml.SafeLoader):
        pass

    def _construct_mapping(loader, node):
        loader.flatten_mapping(node)
        pairs = loader.construct_pairs(node, deep=True)
        d = _LineDict()
        d._line = node.start_mark.line + 1
        seen = {}
        for k, v in pairs:
            if k in seen:
                print(f"  {Y}[WARN]{X} Duplicate key '{k}' at line {node.start_mark.line + 1} — later value overwrites earlier (use a list for multiple blocks)")
            seen[k] = True
            d[k] = v
        return d

    _Loader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, _construct_mapping)
    return yaml.load(text, Loader=_Loader)
